version: '3.8'

services:
  nginx-health:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nginx-health-demo
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=8080"
      - "traefik.http.services.nginx.loadbalancer.healthcheck.path=/health"

  # Optional load balancer to demonstrate health checks
  traefik:
    image: traefik:v2.10
    container_name: traefik-lb
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --healthcheck.interval=10s
    ports:
      - "80:80"
      - "8090:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-health
    profiles: ["loadbalancer"]
